//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<decimal> ABalance { get; set; }
    
        public virtual User User { get; set; }
    }
}
